### PR TITLE
interp: improve support of alias types

### PR DESCRIPTION
**Pull request by tttoad**
I expect the following code to be supported.
```go
type TT http.Header

func (t TT) Set(key, val string) {

}

func (t TT) Get(key string) string {

}
```
So, I pushed this PR. 
Do I need to add some test cases?  I don't see the relevant test files ....

### CODE REVIEW

**Comment by tttoad** [comment]
@mvertes 
Sorry, I always thought I was solving issue-1411...
The problem is that traversing aliasT.
So, I added two test cases.
The case added in alias4.go still does not work.
I need to continue testing this.

**Comment by mvertes** [comment]
@tttoad, I see how to complete your fix. Some other small parts need to be changed as well in `cfg.go` and `typecheck.go`, won't explain there. I'll send those when I'm back from my leave Wednesday.
What you have done is useful and correct, thanks again.

**Comment by tttoad** [comment]
@mvertes You're welcome.

**Review by mvertes — APPROVED** [review]
Looks good to me

**Pull request merged**
